CPPFLAGS=-std=gnu++98 -pedantic -Wall -Werror -ggdb3
all: cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4
cyoa-step1:cyoa-step1.cpp page.h error.h story.h
	g++ $(CPPFLAGS) -o cyoa-step1 cyoa-step1.cpp 
cyoa-step2:cyoa-step2.cpp page.h error.h story.h
	g++ $(CPPFLAGS) -o cyoa-step2 cyoa-step2.cpp
cyoa-step3:cyoa-step3.cpp page.h error.h story.h
	g++ $(CPPFLAGS) -o cyoa-step3 cyoa-step3.cpp
cyoa-step4:cyoa-step4.cpp page.h error.h story.h
	g++ $(CPPFLAGS) -o cyoa-step4 cyoa-step4.cpp
